name: 'Deploy Staging'

on:
  workflow_run:
    workflows: ['Linting']
    types: ['completed']
    branches: ['develop']

jobs:
  deploy-staging:
    name: 'Deploy Staging'
    runs-on: 'ubuntu-latest'
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: 'Deploy'
        uses: 'jbrooksuk/laravel-forge-action@v1.0.2'
        with:
          trigger_url: '${{ secrets.FORGE_STAGING_TRIGGER_URL }}'
